[theme]

# Primary accent for interactive elements
primaryColor = '#C89B3C'

# Background color for the main content area
backgroundColor = '#010A13'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#091428'

# Color used for almost all text
textColor = '#F0E6D2'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"